export const formatDateTime = (isoString) => {
  const date = new Date(isoString);

  const day = date.getDate();
  const monthNames = [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ];
  const month = monthNames[date.getMonth()];
  const year = date.getFullYear();

  let hours = date.getHours();
  const minutes = date.getMinutes().toString().padStart(2, "0");
  const period = hours >= 12 ? "PM" : "AM";

  hours = hours % 12 || 12;

  return `${day} ${month} ${year} - ${hours}:${minutes} ${period}`;
};

export const validCurrencyCodes = [
  { code: "AED", name: "UAE Dirham" },
  { code: "AFN", name: "Afghan Afghani" },
  { code: "ALL", name: "Albanian Lek" },
  { code: "AMD", name: "Armenian Dram" },
  { code: "ANG", name: "Netherlands Antillean Guilder" },
  { code: "AOA", name: "Angolan Kwanza" },
  { code: "ARS", name: "Argentine Peso" },
  { code: "AUD", name: "Australian Dollar" },
  { code: "AWG", name: "Aruban Florin" },
  { code: "AZN", name: "Azerbaijani Manat" },
  { code: "BAM", name: "Bosnia and Herzegovina Convertible Mark" },
  { code: "BBD", name: "Barbadian Dollar" },
  { code: "BDT", name: "Bangladeshi Taka" },
  { code: "BGN", name: "Bulgarian Lev" },
  { code: "BHD", name: "Bahraini Dinar" },
  { code: "BIF", name: "Burundian Franc" },
  { code: "BMD", name: "Bermudian Dollar" },
  { code: "BND", name: "Brunei Dollar" },
  { code: "BOB", name: "Bolivian Boliviano" },
  { code: "BRL", name: "Brazilian Real" },
  { code: "BSD", name: "Bahamian Dollar" },
  { code: "BTN", name: "Bhutanese Ngultrum" },
  { code: "BWP", name: "Botswana Pula" },
  { code: "BYN", name: "Belarusian Ruble" },
  { code: "BZD", name: "Belize Dollar" },
  { code: "CAD", name: "Canadian Dollar" },
  { code: "CDF", name: "Congolese Franc" },
  { code: "CHF", name: "Swiss Franc" },
  { code: "CLP", name: "Chilean Peso" },
  { code: "CNY", name: "Chinese Yuan" },
  { code: "COP", name: "Colombian Peso" },
  { code: "CRC", name: "Costa Rican Colón" },
  { code: "CUP", name: "Cuban Peso" },
  { code: "CVE", name: "Cape Verdean Escudo" },
  { code: "CZK", name: "Czech Koruna" },
  { code: "DJF", name: "Djiboutian Franc" },
  { code: "DKK", name: "Danish Krone" },
  { code: "DOP", name: "Dominican Peso" },
  { code: "DZD", name: "Algerian Dinar" },
  { code: "EGP", name: "Egyptian Pound" },
  { code: "ERN", name: "Eritrean Nakfa" },
  { code: "ETB", name: "Ethiopian Birr" },
  { code: "EUR", name: "Euro" },
  { code: "FJD", name: "Fijian Dollar" },
  { code: "FKP", name: "Falkland Islands Pound" },
  { code: "GBP", name: "British Pound Sterling" },
  { code: "GEL", name: "Georgian Lari" },
  { code: "GHS", name: "Ghanaian Cedi" },
  { code: "GIP", name: "Gibraltar Pound" },
  { code: "GMD", name: "Gambian Dalasi" },
  { code: "GNF", name: "Guinean Franc" },
  { code: "GTQ", name: "Guatemalan Quetzal" },
  { code: "GYD", name: "Guyanese Dollar" },
  { code: "HKD", name: "Hong Kong Dollar" },
  { code: "HNL", name: "Honduran Lempira" },
  { code: "HRK", name: "Croatian Kuna" },
  { code: "HTG", name: "Haitian Gourde" },
  { code: "HUF", name: "Hungarian Forint" },
  { code: "IDR", name: "Indonesian Rupiah" },
  { code: "ILS", name: "Israeli New Shekel" },
  { code: "INR", name: "Indian Rupee" },
  { code: "IQD", name: "Iraqi Dinar" },
  { code: "IRR", name: "Iranian Rial" },
  { code: "ISK", name: "Icelandic Króna" },
  { code: "JMD", name: "Jamaican Dollar" },
  { code: "JOD", name: "Jordanian Dinar" },
  { code: "JPY", name: "Japanese Yen" },
  { code: "KES", name: "Kenyan Shilling" },
  { code: "KGS", name: "Kyrgyzstani Som" },
  { code: "KHR", name: "Cambodian Riel" },
  { code: "KMF", name: "Comorian Franc" },
  { code: "KRW", name: "South Korean Won" },
  { code: "KWD", name: "Kuwaiti Dinar" },
  { code: "KYD", name: "Cayman Islands Dollar" },
  { code: "KZT", name: "Kazakhstani Tenge" },
  { code: "LAK", name: "Laotian Kip" },
  { code: "LBP", name: "Lebanese Pound" },
  { code: "LKR", name: "Sri Lankan Rupee" },
  { code: "LRD", name: "Liberian Dollar" },
  { code: "LSL", name: "Lesotho Loti" },
  { code: "LTL", name: "Lithuanian Litas" },
  { code: "LVL", name: "Latvian Lats" },
  { code: "LYD", name: "Libyan Dinar" },
  { code: "MAD", name: "Moroccan Dirham" },
  { code: "MDL", name: "Moldovan Leu" },
  { code: "MGA", name: "Malagasy Ariary" },
  { code: "MKD", name: "Macedonian Denar" },
  { code: "MMK", name: "Myanma Kyat" },
  { code: "MNT", name: "Mongolian Tugrik" },
  { code: "MOP", name: "Macanese Pataca" },
  { code: "MRU", name: "Mauritanian Ouguiya" },
  { code: "MUR", name: "Mauritian Rupee" },
  { code: "MVR", name: "Maldivian Rufiyaa" },
  { code: "MWK", name: "Malawian Kwacha" },
  { code: "MXN", name: "Mexican Peso" },
  { code: "MYR", name: "Malaysian Ringgit" },
  { code: "MZN", name: "Mozambican Metical" },
  { code: "NAD", name: "Namibian Dollar" },
  { code: "NGN", name: "Nigerian Naira" },
  { code: "NIO", name: "Nicaraguan Córdoba" },
  { code: "NOK", name: "Norwegian Krone" },
  { code: "NPR", name: "Nepalese Rupee" },
  { code: "NZD", name: "New Zealand Dollar" },
  { code: "OMR", name: "Omani Rial" },
  { code: "PAB", name: "Panamanian Balboa" },
  { code: "PEN", name: "Peruvian Nuevo Sol" },
  { code: "PGK", name: "Papua New Guinean Kina" },
  { code: "PHP", name: "Philippine Peso" },
  { code: "PKR", name: "Pakistani Rupee" },
  { code: "PLN", name: "Polish Zloty" },
  { code: "PYG", name: "Paraguayan Guarani" },
  { code: "QAR", name: "Qatari Rial" },
  { code: "RON", name: "Romanian Leu" },
  { code: "RSD", name: "Serbian Dinar" },
  { code: "RUB", name: "Russian Ruble" },
  { code: "RWF", name: "Rwandan Franc" },
  { code: "SAR", name: "Saudi Riyal" },
  { code: "SBD", name: "Solomon Islands Dollar" },
  { code: "SCR", name: "Seychelles Rupee" },
  { code: "SEK", name: "Swedish Krona" },
  { code: "SGD", name: "Singapore Dollar" },
  { code: "SHP", name: "Saint Helena Pound" },
  { code: "SLL", name: "Sierra Leonean Leone" },
  { code: "SOS", name: "Somali Shilling" },
  { code: "SRD", name: "Surinamese Dollar" },
  { code: "SSP", name: "South Sudanese Pound" },
  { code: "STN", name: "São Tomé and Príncipe Dobra" },
  { code: "SYP", name: "Syrian Pound" },
  { code: "SZL", name: "Swazi Lilangeni" },
  { code: "THB", name: "Thai Baht" },
  { code: "TJS", name: "Tajikistani Somoni" },
  { code: "TMT", name: "Turkmenistani Manat" },
  { code: "TND", name: "Tunisian Dinar" },
  { code: "TOP", name: "Tongan Paʻanga" },
  { code: "TRY", name: "Turkish Lira" },
  { code: "TTD", name: "Trinidad and Tobago Dollar" },
  { code: "TWD", name: "New Taiwan Dollar" },
  { code: "TZS", name: "Tanzanian Shilling" },
  { code: "UAH", name: "Ukrainian Hryvnia" },
  { code: "UGX", name: "Ugandan Shilling" },
  { code: "UYU", name: "Uruguayan Peso" },
  { code: "UZS", name: "Uzbekistani Som" },
  { code: "VEF", name: "Venezuelan Bolívar" },
  { code: "VND", name: "Vietnamese Dong" },
  { code: "VUV", name: "Vanuatu Vatu" },
  { code: "WST", name: "Samoan Tala" },
  { code: "XAF", name: "CFA Franc BEAC" },
  { code: "XCD", name: "East Caribbean Dollar" },
  { code: "XOF", name: "CFA Franc West African" },
  { code: "XPF", name: "CFP Franc" },
  { code: "YER", name: "Yemeni Rial" },
  { code: "ZAR", name: "South African Rand" },
  { code: "ZMW", name: "Zambian Kwacha" },
  { code: "ZWL", name: "Zimbabwean Dollar" },
];

export const countryCurCode = [
  { country: "UAE", code: "AED" },
  { country: "Afghanistan", code: "AFN" },
  { country: "Albania", code: "ALL" },
  { country: "Armenia", code: "AMD" },
  { country: "Netherlands Antilles", code: "ANG" },
  { country: "Angola", code: "AOA" },
  { country: "Argentina", code: "ARS" },
  { country: "Australia", code: "AUD" },
  { country: "Aruba", code: "AWG" },
  { country: "Azerbaijan", code: "AZN" },
  { country: "Bosnia and Herzegovina", code: "BAM" },
  { country: "Barbados", code: "BBD" },
  { country: "Bangladesh", code: "BDT" },
  { country: "Bulgaria", code: "BGN" },
  { country: "Bahrain", code: "BHD" },
  { country: "Burundi", code: "BIF" },
  { country: "Bermuda", code: "BMD" },
  { country: "Brunei", code: "BND" },
  { country: "Bolivia", code: "BOB" },
  { country: "Brazil", code: "BRL" },
  { country: "Bahamas", code: "BSD" },
  { country: "Bhutan", code: "BTN" },
  { country: "Botswana", code: "BWP" },
  { country: "Belarus", code: "BYN" },
  { country: "Belize", code: "BZD" },
  { country: "Canada", code: "CAD" },
  { country: "Congo (DRC)", code: "CDF" },
  { country: "Switzerland", code: "CHF" },
  { country: "Chile", code: "CLP" },
  { country: "China", code: "CNY" },
  { country: "Colombia", code: "COP" },
  { country: "Costa Rica", code: "CRC" },
  { country: "Cuba", code: "CUP" },
  { country: "Cape Verde", code: "CVE" },
  { country: "Czech Republic", code: "CZK" },
  { country: "Djibouti", code: "DJF" },
  { country: "Denmark", code: "DKK" },
  { country: "Dominican Republic", code: "DOP" },
  { country: "Algeria", code: "DZD" },
  { country: "Egypt", code: "EGP" },
  { country: "Eritrea", code: "ERN" },
  { country: "Ethiopia", code: "ETB" },
  { country: "Eurozone", code: "EUR" },
  { country: "Fiji", code: "FJD" },
  { country: "Falkland Islands", code: "FKP" },
  { country: "United Kingdom", code: "GBP" },
  { country: "Georgia", code: "GEL" },
  { country: "Ghana", code: "GHS" },
  { country: "Gibraltar", code: "GIP" },
  { country: "Gambia", code: "GMD" },
  { country: "Guinea", code: "GNF" },
  { country: "Guatemala", code: "GTQ" },
  { country: "Guyana", code: "GYD" },
  { country: "Hong Kong", code: "HKD" },
  { country: "Honduras", code: "HNL" },
  { country: "Croatia", code: "HRK" },
  { country: "Haiti", code: "HTG" },
  { country: "Hungary", code: "HUF" },
  { country: "Indonesia", code: "IDR" },
  { country: "Israel", code: "ILS" },
  { country: "India", code: "INR" },
  { country: "Iraq", code: "IQD" },
  { country: "Iran", code: "IRR" },
  { country: "Iceland", code: "ISK" },
  { country: "Jamaica", code: "JMD" },
  { country: "Jordan", code: "JOD" },
  { country: "Japan", code: "JPY" },
  { country: "Kenya", code: "KES" },
  { country: "Kyrgyzstan", code: "KGS" },
  { country: "Cambodia", code: "KHR" },
  { country: "Comoros", code: "KMF" },
  { country: "South Korea", code: "KRW" },
  { country: "Kuwait", code: "KWD" },
  { country: "Cayman Islands", code: "KYD" },
  { country: "Kazakhstan", code: "KZT" },
  { country: "Laos", code: "LAK" },
  { country: "Lebanon", code: "LBP" },
  { country: "Sri Lanka", code: "LKR" },
  { country: "Liberia", code: "LRD" },
  { country: "Lesotho", code: "LSL" },
  { country: "Lithuania", code: "LTL" },
  { country: "Latvia", code: "LVL" },
  { country: "Libya", code: "LYD" },
  { country: "Morocco", code: "MAD" },
  { country: "Moldova", code: "MDL" },
  { country: "Madagascar", code: "MGA" },
  { country: "North Macedonia", code: "MKD" },
  { country: "Myanmar", code: "MMK" },
  { country: "Mongolia", code: "MNT" },
  { country: "Macau", code: "MOP" },
  { country: "Mauritania", code: "MRU" },
  { country: "Mauritius", code: "MUR" },
  { country: "Maldives", code: "MVR" },
  { country: "Malawi", code: "MWK" },
  { country: "Mexico", code: "MXN" },
  { country: "Malaysia", code: "MYR" },
  { country: "Mozambique", code: "MZN" },
  { country: "Namibia", code: "NAD" },
  { country: "Nigeria", code: "NGN" },
  { country: "Nicaragua", code: "NIO" },
  { country: "Norway", code: "NOK" },
  { country: "Nepal", code: "NPR" },
  { country: "New Zealand", code: "NZD" },
  { country: "Oman", code: "OMR" },
  { country: "Panama", code: "PAB" },
  { country: "Peru", code: "PEN" },
  { country: "Papua New Guinea", code: "PGK" },
  { country: "Philippines", code: "PHP" },
  { country: "Pakistan", code: "PKR" },
  { country: "Poland", code: "PLN" },
  { country: "Paraguay", code: "PYG" },
  { country: "Qatar", code: "QAR" },
  { country: "Romania", code: "RON" },
  { country: "Serbia", code: "RSD" },
  { country: "Russia", code: "RUB" },
  { country: "Rwanda", code: "RWF" },
  { country: "Saudi Arabia", code: "SAR" },
  { country: "Solomon Islands", code: "SBD" },
  { country: "Seychelles", code: "SCR" },
  { country: "Sweden", code: "SEK" },
  { country: "Singapore", code: "SGD" },
  { country: "Saint Helena", code: "SHP" },
  { country: "Sierra Leone", code: "SLL" },
  { country: "Somalia", code: "SOS" },
  { country: "Suriname", code: "SRD" },
  { country: "South Sudan", code: "SSP" },
  { country: "São Tomé and Príncipe", code: "STN" },
  { country: "Syria", code: "SYP" },
  { country: "Eswatini", code: "SZL" },
  { country: "Thailand", code: "THB" },
  { country: "Tajikistan", code: "TJS" },
  { country: "Turkmenistan", code: "TMT" },
  { country: "Tunisia", code: "TND" },
  { country: "Tonga", code: "TOP" },
  { country: "Turkey", code: "TRY" },
  { country: "Trinidad and Tobago", code: "TTD" },
  { country: "Taiwan", code: "TWD" },
  { country: "Tanzania", code: "TZS" },
  { country: "Ukraine", code: "UAH" },
  { country: "Uganda", code: "UGX" },
  { country: "Uruguay", code: "UYU" },
  { country: "Uzbekistan", code: "UZS" },
  { country: "Venezuela", code: "VEF" },
  { country: "Vietnam", code: "VND" },
  { country: "Vanuatu", code: "VUV" },
  { country: "Samoa", code: "WST" },
  { country: "Central African CFA", code: "XAF" },
  { country: "East Caribbean", code: "XCD" },
  { country: "West African CFA", code: "XOF" },
  { country: "Pacific CFA", code: "XPF" },
  { country: "Yemen", code: "YER" },
  { country: "South Africa", code: "ZAR" },
  { country: "Zambia", code: "ZMW" },
  { country: "Zimbabwe", code: "ZWL" },
];
